version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    depends_on:
      postgres:
        condition: service_started
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/mydatabase
