FROM postgres:latest

ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin
ENV POSTGRES_DB=mydatabase

EXPOSE 5432

HEALTHCHECK --interval=30s --timeout=10s --retries=5 \
  CMD pg_isready -U $POSTGRES_USER || exit 1
